# Generated by Django 3.2.25 on 2025-03-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C3_app1', '0003_auto_20250326_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
