# Generated by Django 3.2.25 on 2025-03-27 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('C3_app1', '0004_alter_product_dealership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.AddField(
            model_name='sale',
            name='dealership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='C3_app1.dealership'),
        ),
        migrations.AddField(
            model_name='sale',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='product_sold',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='C3_app1.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
