# Generated by Django 3.2.25 on 2025-03-27 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('C3_app1', '0005_auto_20250327_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='dealership',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='C3_app1.dealership'),
            preserve_default=False,
        ),
    ]
