# Generated by Django 3.2.25 on 2025-03-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C3_app1', '0006_alter_sale_dealership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
