# Generated by Django 3.2.25 on 2025-04-03 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('C3_app1', '0010_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='dealership',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='C3_app1.dealership'),
            preserve_default=False,
        ),
    ]
