# Generated by Django 3.2.25 on 2025-04-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C3_app1', '0016_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reorder_threshold',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
