# Generated by Django 3.2.25 on 2025-04-08 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('C3_app1', '0017_product_reorder_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='dealership',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='C3_app1.dealership'),
        ),
    ]
