# Generated by Django 3.2.25 on 2025-04-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C3_app1', '0017_coreproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
