# Generated by Django 3.2.25 on 2025-04-08 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('C3_app1', '0018_claim_dealership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='dealership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='C3_app1.dealership'),
        ),
    ]
